Serhioromano/bootstrap-calendar

- js/language/ms-MY.js
Add translation for Bahasa Malaysia
> Add Bahasa Malaysia support

- index-bs3.html
- index.html
- js/app.js
- js/calendar.js
This addresses gh-494 and gh-316
> Allow 12/24 hour formatting

- index-bs3.html
- index.html
- js/language/th-TH.js
Hi Serhioromano,
Thank you for your code and everybody from this community. After used it, I created new Thai language support for this Respo and think I need to share it back as well.
Thanks again,
Porrapat
> Add Thai language support.

- js/language/fi-FI.js
Reworked my earlier pull request.
> Add some finnish holidays.

- js/language/de-DE.js
> Updated german holidays

- js/language/ca-ES.js
> Catalonian translation

- js/language/id-ID.js
Add 2016 indonesian holidays and fix typo
> Add 2016 indonesian holidays

- js/calendar.js
- js/language/bg-BG.js
- js/language/bs-BA.js
- js/language/ca-ES.js
- js/language/cs-CZ.js
- js/language/da-DK.js
- js/language/de-AT.js
- js/language/de-DE.js
- js/language/el-GR.js
- js/language/es-CO.js
- js/language/es-ES.js
- js/language/es-MX.js
- js/language/fi-FI.js
- js/language/fr-FR.js
- js/language/hr-HR.js
- js/language/hu-HU.js
- js/language/id-ID.js
- js/language/it-IT.js
- js/language/ms-MY.js
- js/language/nl-NL.js
- js/language/no-NO.js
- js/language/pl-PL.js
- js/language/ro-RO.js
- js/language/ru-RU.js
- js/language/sk-SR.js
- js/language/sl-SL.js
- js/language/sv-SE.js
- js/language/template.js
- js/language/th-TH.js
- js/language/tr-TR.js
Fixes #476
Introduces a new extended option called "week_numbers_iso_8601"
Locales adapted according to https://en.wikipedia.org/wiki/Week#Week_numbering
> Add week number ISO 8601 setting

- js/calendar.js
> Calculate utc offset from start and end dates instead the actual date

- js/calendar.js
Sometimes you need a option to add the tooltip not direct to body
> Add option to define a tooltip container

- js/calendar.js
As you mention [in previous mr](https://github.com/Serhioromano/bootstrap-calendar/pull/637#issuecomment-235310897). I add an additional parameter.
> add option which hides events which not feets time

- js/calendar.js
Add a little code snippet to allow sending headers params on ajax call
> Add headers parameters

- tmpls/year.html
Fixes issue with calendar year columns not aligning on smaller screens (i.e. < 992px)
> Responsive year layout for small screens

- index-bs3.html
- index.html
- js/language/es-CL.js
Added Chilean Spanish to the demo page
> add chilean spanish translation

- index-bs3.html
- index.html
- js/language/es-DO.js
Added file translation for Dominican Republic
> Created file es-DO.js

- js/language/lv-LV.js
New language file with Latvian translation.
> Latvian language translation

- js/language/lt-LT.js
> Add lithuanian translations

- README.md
Instead of the old screenshot, provides a gif of month view to show some things the calndar can do.
Also add borders to the screenshot: it is easier to see that's a picture and where it begins/ends.
> Edit the plugin preview

- js/language/id-ID.js
Add Public Holidays in Indonesia in 2018 and fix typo
> Add Public Holidays in Indonesia in 2018

- README.md
Without this for understand the functionality of `modal_title` option we need to search in calendar.js code
> Added .modal-title to event modal
